# Generated by Django 3.2.18 on 2023-05-17 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60, unique=True)),
                ('customer_key', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('domain', models.CharField(max_length=60, unique=True)),
                ('allow_admin_rate_upload', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=30)),
                ('instance_type', models.CharField(choices=[('DEV', 'DEV'), ('SIT', 'SIT'), ('UAT', 'UAT'), ('PATCH', 'PATCH'), ('PROD', 'PROD')], max_length=30)),
                ('otm_url', models.URLField()),
                ('otm_user', models.CharField(max_length=30)),
                ('otm_password', fernet_fields.fields.EncryptedCharField(max_length=1000)),
                ('passkey_enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
            ],
            options={
                'unique_together': {('customer', 'instance_name')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='DEFAULT', max_length=30, null=True)),
                ('offering_type_name', models.CharField(choices=[('AIR', 'Air'), ('FCL', 'FCL (Full Container Load)'), ('LCL', 'LCL (Less than Container Load)'), ('LTL', 'LTL (Less than Truckload)'), ('TL', 'TL (Truckload)')], max_length=30)),
                ('offering_type_description', models.CharField(blank=True, max_length=30)),
                ('rate_type_name', models.CharField(choices=[('Container', 'Container'), ('Flat', 'Flat'), ('Volume', 'Volume'), ('Weight', 'Weight'), ('Weight Break', 'Weight Break'), ('Discount', 'Discount')], max_length=30)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'unique_together': {('customer', 'offering_type_name', 'rate_type_name', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateDynamicColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=30)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('position', models.IntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.template')),
            ],
            options={
                'verbose_name': 'Template Dynamic Column',
                'verbose_name_plural': 'Template Dynamic Columns',
                'unique_together': {('customer', 'template', 'parameter_name')},
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_type', models.CharField(choices=[('VOLUME', 'Volume'), ('WEIGHT', 'Weight')], max_length=20)),
                ('uom_code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'unique_together': {('uom_type', 'uom_code')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=10)),
                ('group_name', models.CharField(blank=True, default='DEFAULT', max_length=50)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('sub_group', models.CharField(blank=True, default='', max_length=50)),
                ('tag', models.CharField(blank=True, default='', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sequence', models.IntegerField(blank=True)),
                ('csv_file_name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('file_identifier', models.CharField(blank=True, max_length=30)),
                ('has_date_field', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('date_format', models.CharField(blank=True, default='YYYYMMDDHH24MISS', max_length=30)),
                ('auto_remove_duplicates', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('auto_number_initial_sequence', models.IntegerField(blank=True, null=True)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
            ],
            options={
                'verbose_name': 'CSV File',
                'verbose_name_plural': 'CSV Files',
                'unique_together': {('customer', 'csv_file_name'), ('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access',
                'verbose_name_plural': 'User Accesses',
                'unique_together': {('user', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='TemplateStaticColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_column_name', models.CharField(max_length=30)),
                ('master_column_name', models.CharField(max_length=30)),
                ('enterable', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('required', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('include_in_template', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('position', models.IntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.template')),
            ],
            options={
                'verbose_name': 'Template Static Column',
                'verbose_name_plural': 'Template Static Columns',
                'unique_together': {('customer', 'template', 'template_column_name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateDynamicColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('parameter_value', models.CharField(max_length=30)),
                ('default_selected', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('template_column_names', models.CharField(blank=True, max_length=1000)),
                ('master_column_names', models.CharField(blank=True, max_length=1000)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.templatedynamiccolumn')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.template')),
            ],
            options={
                'verbose_name': 'Template Dynamic Column Value',
                'verbose_name_plural': 'Template Dynamic Columns Values',
                'unique_together': {('customer', 'template', 'param', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='DEFAULT', max_length=30)),
                ('attribute1', models.CharField(blank=True, max_length=100)),
                ('attribute2', models.CharField(blank=True, max_length=100)),
                ('attribute3', models.CharField(blank=True, max_length=100)),
                ('attribute4', models.CharField(blank=True, max_length=100)),
                ('attribute5', models.CharField(blank=True, max_length=100)),
                ('attribute6', models.CharField(blank=True, max_length=100)),
                ('attribute7', models.CharField(blank=True, max_length=100)),
                ('attribute8', models.CharField(blank=True, max_length=100)),
                ('attribute9', models.CharField(blank=True, max_length=100)),
                ('attribute10', models.CharField(blank=True, max_length=100)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'unique_together': {('customer', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='CsvStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('column_name', models.CharField(max_length=30)),
                ('source_column_name', models.CharField(blank=True, max_length=30)),
                ('fixed_value', models.CharField(blank=True, max_length=30)),
                ('expression', models.TextField(blank=True, max_length=1000)),
                ('enabled', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.csvfile')),
            ],
            options={
                'verbose_name': 'CSV File Field',
                'verbose_name_plural': 'CSV File Fields',
                'unique_together': {('csv_file', 'sequence'), ('csv_file', 'column_name')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=60)),
                ('field_values', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.template')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'unique_together': {('customer', 'template', 'batch_name')},
            },
        ),
    ]
