# Generated by Django 3.2.18 on 2023-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_csvfile_csv_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_command',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file_identifier',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
