# Generated by Django 3.2.18 on 2023-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20230517_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedynamiccolumnvalue',
            name='master_column_names',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='templatedynamiccolumnvalue',
            name='template_column_names',
            field=models.CharField(max_length=1000),
        ),
    ]
