# Generated by Django 3.2.18 on 2023-05-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20230517_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='view_all_template_batch',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=1),
        ),
    ]
